# stage 1
FROM alpine:latest

COPY my-node-code /app
RUN npm build && do stuff to create content

# stage 2
FROM alpine:latest

COPY --from=0 /app/assets/public /data/web/site
COPY . /app/nginx

# bring in nginx
RUN apk --no-cache add nginx && mkdir -p /data/{nginx,web}


ARG BUILD_VERSION

# CCE-26895-3 - Ensure Software Patches Applied every build
RUN echo $BUILD_VERSION && apk upgrade --no-cache

EXPOSE 80
EXPOSE 443
STOPSIGNAL SIGQUIT

# bring in your SSL keys some way (or see Dockerfile-reflex)
ENTRYPOINT /app/nginx/entrypoint.sh
